title: Wingman System Status
baseURL: https://status.trywingman.com
languageCode: en
params:
  shortDateFormat: 15:04 — Jan 2
  meta_description: >-
    Wingman System Status


    Welcome to Wingman’s home for real-time and historical data on our system performance.
  systems:
    - name: AWS (us-east-1)
      description: Our cloud infrastructure provider
      link: ""
    - name: Call Recorders
      description: "Call Recorders: Our recording bots, which join and record video
        conference calls"
      link: ""
    - name: CRM Integrations
      description: Wingman's integration with CRMs to pull calls and update notes,
        comments etc
    - name: Web App
      link: https://app.trywingman.com
    - name: Desktop App
      description: Your friendly desktop helper
    - name: API
      description: https://rest-api.trywingman.com
  dateFormat: January 2, 2006 at 3:04 PM
  disqusShortname: null
  timezoneString: PST
  logo: /images/uploads/wingmanlogo.svg
  description_header: >-
    If you are facing an issue that is not reported here, please let us know at
    support@trywingman.com.

    <br/><br/>

    Subscribe <a class='text-grey-darkest' href='%s'>here</a> to be alerted of new events [coming soon].
  copyrightHolder: Strings Systems Inc.
  eventsPerPage: 10
  iconType: image/png
  groups:
    - CRMIntegrations
  icon: /images/clearstatus.png
  description_footer: <a class='text-grey-darkest' title='Visit trywingman.com'
    href='https://www.trywingman.com/'>Wingman</a> helps sales teams pitch
    better and close faster.
