title: "Wingman: Real-time operational status"
baseURL: https://status.trywingman.com
languageCode: en
params:
  shortDateFormat: 15:04 — Jan 2
  meta_description: This status page provides updated information about our
    systems normal operation, incidents that may happen and their resolution. If
    you are facing an issue that is not reported here, please let us know
    at 	support@trywingman.com
  systems:
    - name: AWS (us-east-1)
      description: "Our cloud infrastructure provider:"
      link: ""
    - name: Call Recorders
      description: Our recording bots which join and record Video Conference Calls
      link: https://support.example.com/
    - name: CRM Integrations
      description: Wingman's integration with CRMs to pull calls and update notes,
        comments etc
    - name: Web App
      link: https://app.trywingman.com
    - name: Desktop App
      description: Your friendly desktop helper
    - name: API
      description: https://rest-api.trywingman.com
  dateFormat: January 2, 2006 at 3:04 PM
  disqusShortname: null
  timezoneString: PST
  logo: /images/uploads/wingmanlogo.svg
  description_header: ""
  copyrightHolder: Strings Systems Inc.
  eventsPerPage: 10
  iconType: image/png
  groups:
    - CRMIntegrations
  icon: /images/clearstatus.png
  description_footer: <a class='text-grey-darkest' title='Visit trywingman.com'
    href='https://www.trywingman.com/'>Wingman</a> provides the best software
    for sales professionals to close more deals.
